### PR TITLE
Add create_ronly_buffer and create_wonly_buffer

### LINKED ISSUE #18: Add functions to create read-only and write-only buffers
Equivalent to the existing `create_rw_buffer` function.

### PR DESCRIPTION
**Pull request by sergisiso**
Closes #18

Small update to act on the reviewer suggestion on https://github.com/stfc/PSyclone/pull/1175

### CODE REVIEW

**Comment by sergisiso** [comment]
@arporter A small PR to make some of the Psyclone-generated buffers read-only. Ready for review.

**Review by arporter — CHANGES_REQUESTED** [review]
New code looks fine.
Would it be possible to add the use of one or both of the new routines to one or more of the examples (e.g examples/vadd/vaddhost.f90)?

**Comment by sergisiso** [comment]
@arporter I added them in the examples as suggested. Ready for next review.

**Review by arporter — APPROVED** [review]
Perfect. Thanks for extending the examples.

**Pull request merged**
